/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JogosContarRouteImport } from './routes/jogos/contar'
import { Route as JogosCoresRouteImport } from './routes/jogos/cores'
import { Route as JogosFormasRouteImport } from './routes/jogos/formas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosContarRoute = JogosContarRouteImport.update({
  id: '/jogos/contar',
  path: '/jogos/contar',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosCoresRoute = JogosCoresRouteImport.update({
  id: '/jogos/cores',
  path: '/jogos/cores',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosFormasRoute = JogosFormasRouteImport.update({
  id: '/jogos/formas',
  path: '/jogos/formas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jogos/contar': typeof JogosContarRoute
  '/jogos/cores': typeof JogosCoresRoute
  '/jogos/formas': typeof JogosFormasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jogos/contar': typeof JogosContarRoute
  '/jogos/cores': typeof JogosCoresRoute
  '/jogos/formas': typeof JogosFormasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jogos/contar': typeof JogosContarRoute
  '/jogos/cores': typeof JogosCoresRoute
  '/jogos/formas': typeof JogosFormasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jogos/contar' | '/jogos/cores' | '/jogos/formas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jogos/contar' | '/jogos/cores' | '/jogos/formas'
  id: '__root__' | '/' | '/jogos/contar' | '/jogos/cores' | '/jogos/formas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JogosContarRoute: typeof JogosContarRoute
  JogosCoresRoute: typeof JogosCoresRoute
  JogosFormasRoute: typeof JogosFormasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/contar': {
      id: '/jogos/contar'
      path: '/jogos/contar'
      fullPath: '/jogos/contar'
      preLoaderRoute: typeof JogosContarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/cores': {
      id: '/jogos/cores'
      path: '/jogos/cores'
      fullPath: '/jogos/cores'
      preLoaderRoute: typeof JogosCoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/formas': {
      id: '/jogos/formas'
      path: '/jogos/formas'
      fullPath: '/jogos/formas'
      preLoaderRoute: typeof JogosFormasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JogosContarRoute: JogosContarRoute,
  JogosCoresRoute: JogosCoresRoute,
  JogosFormasRoute: JogosFormasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
